# Generated by Django 3.2.5 on 2021-07-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_branchinformation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinformation',
            name='Branch_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
