# Generated by Django 3.2.5 on 2021-07-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_branchinformation_branch_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchInformation',
            new_name='BranchInformationM',
        ),
    ]
