# Generated by Django 3.2.5 on 2021-07-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_rename_branchinformation_branchinformationm'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinformationm',
            name='Company_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
