# Generated by Django 3.2.5 on 2021-07-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_branchinformationm_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchinformationm',
            old_name='Branch_Logo',
            new_name='BranchLogo',
        ),
    ]
