# Generated by Django 3.2.5 on 2021-07-15 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0008_remove_userprofilem_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserBranchM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Branch_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.branchinformationm')),
                ('User_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
