# Generated by Django 3.2.7 on 2021-10-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_auto_20210715_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesinfoM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Father_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Mother_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Married', models.CharField(blank=True, max_length=255, null=True)),
                ('Spouse_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Sex', models.CharField(blank=True, max_length=255, null=True)),
                ('Birth_Date', models.DateField(blank=True, null=True)),
                ('Present_Address', models.TextField(blank=True, null=True)),
                ('Permanant_Address', models.TextField(blank=True, null=True)),
                ('Phone', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Nid', models.CharField(blank=True, max_length=255, null=True)),
                ('Joining_Date', models.DateField(blank=True, null=True)),
                ('Probationary_Period', models.CharField(blank=True, max_length=50, null=True)),
                ('Confirmation_dates', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Emp_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.branchinformationm')),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.department')),
                ('Designationas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.designation')),
            ],
        ),
        migrations.CreateModel(
            name='TransitBy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoyageVia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesSalary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('Effect_Date', models.DateField(blank=True, null=True)),
                ('Basic', models.IntegerField(blank=True, null=True)),
                ('House_Rent', models.IntegerField(blank=True, null=True)),
                ('House_Maintenance', models.IntegerField(blank=True, null=True)),
                ('Hospital_Allowance', models.IntegerField(blank=True, null=True)),
                ('Conveyance_Allowance', models.IntegerField(blank=True, null=True)),
                ('Entertainment_Allowance', models.IntegerField(blank=True, null=True)),
                ('Other', models.IntegerField(blank=True, null=True)),
                ('Gross', models.IntegerField(blank=True, null=True)),
                ('Income_Tax', models.IntegerField(blank=True, null=True)),
                ('Ename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.employeesinfom')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesEducation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Exam_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Institute', models.CharField(blank=True, max_length=255, null=True)),
                ('Board', models.CharField(blank=True, max_length=50, null=True)),
                ('Pass_Year', models.CharField(blank=True, max_length=50, null=True)),
                ('Gpa', models.CharField(blank=True, max_length=50, null=True)),
                ('Ename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.employeesinfom')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Client_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.branchinformationm')),
            ],
        ),
        migrations.CreateModel(
            name='ClentAddressInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(blank=True, max_length=700, null=True)),
                ('Phone', models.CharField(blank=True, max_length=55, null=True)),
                ('Email', models.EmailField(blank=True, max_length=55, null=True)),
                ('Client_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.clientinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Bankinformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Bank_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.branchinformationm')),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Branch_Name', models.CharField(blank=True, max_length=700, null=True)),
                ('Address', models.CharField(blank=True, max_length=700, null=True)),
                ('Phone', models.CharField(blank=True, max_length=55, null=True)),
                ('Email', models.EmailField(blank=True, max_length=55, null=True)),
                ('Bank_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.bankinformation')),
            ],
        ),
    ]
