# Generated by Django 3.2.5 on 2021-07-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_auto_20210715_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesinfoM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Department', models.CharField(blank=True, max_length=255, null=True)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('Father_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Mother_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Married', models.CharField(blank=True, max_length=255, null=True)),
                ('Spouse_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Sex', models.CharField(blank=True, max_length=255, null=True)),
                ('Birth_Date', models.DateField(blank=True, null=True)),
                ('Present_Address', models.TextField(blank=True, null=True)),
                ('Permanant_Address', models.TextField(blank=True, null=True)),
                ('Phone', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Nid', models.CharField(blank=True, max_length=255, null=True)),
                ('Joining_Date', models.DateField(blank=True, null=True)),
                ('Probationary_Period', models.CharField(blank=True, max_length=50, null=True)),
                ('Confirmation_dates', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Emp_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.branchinformationm')),
            ],
        ),
    ]
