# Generated by Django 3.2.5 on 2021-07-27 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_employeesinfom'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesSalary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('Effect_Date', models.DateField(blank=True, null=True)),
                ('Basic', models.IntegerField(blank=True, null=True)),
                ('House_Rent', models.IntegerField(blank=True, null=True)),
                ('House_Maintenance', models.IntegerField(blank=True, null=True)),
                ('Hospital_Allowance', models.IntegerField(blank=True, null=True)),
                ('Conveyance_Allowance', models.IntegerField(blank=True, null=True)),
                ('Entertainment_Allowance', models.IntegerField(blank=True, null=True)),
                ('Other', models.IntegerField(blank=True, null=True)),
                ('Gross', models.IntegerField(blank=True, null=True)),
                ('Ename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.employeesinfom')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesEducation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Exam_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Institute', models.CharField(blank=True, max_length=255, null=True)),
                ('Board', models.CharField(blank=True, max_length=50, null=True)),
                ('Pass_Year', models.CharField(blank=True, max_length=50, null=True)),
                ('Gpa', models.CharField(blank=True, max_length=50, null=True)),
                ('Ename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.employeesinfom')),
            ],
        ),
    ]
