# Generated by Django 3.2.5 on 2021-07-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_employeeseducation_employeessalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeessalary',
            name='Income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
