# Generated by Django 3.2.5 on 2021-07-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_employeessalary_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeessalary',
            old_name='Income',
            new_name='Income_Tax',
        ),
    ]
