# Generated by Django 3.2.7 on 2021-10-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0012_voyagefrom_voyageto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarineQuatationM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Bill_date', models.DateField(auto_now=True)),
                ('Bank_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Interest_covered', models.CharField(blank=True, max_length=1000, null=True)),
                ('Sdate', models.DateField(blank=True, null=True)),
                ('Edate', models.DateField(blank=True, null=True)),
                ('Sum_insured', models.IntegerField(blank=True, null=True)),
                ('Extra1', models.IntegerField(blank=True, null=True)),
                ('Extra2', models.IntegerField(blank=True, null=True)),
                ('Currency', models.IntegerField(blank=True, null=True)),
                ('Excrate', models.IntegerField(blank=True, null=True)),
                ('Bdtamount', models.IntegerField(blank=True, null=True)),
                ('Declaration', models.CharField(blank=True, max_length=600, null=True)),
                ('Producer', models.CharField(blank=True, max_length=600, null=True)),
                ('Bank_Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.bankbranch')),
                ('Bank_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.bankinformation')),
                ('Client_AddressM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.clentaddressinformation')),
                ('Client_NameM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.clientinformation')),
                ('Transit_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.transitby')),
                ('Voyage_From', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.voyagefrom')),
                ('Voyage_To', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.voyageto')),
                ('Voyage_Via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.voyagevia')),
            ],
        ),
    ]
