# Generated by Django 3.2.5 on 2021-09-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_rename_income_employeessalary_income_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Client_Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClentAddressInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(blank=True, max_length=700, null=True)),
                ('Client_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.clientinformation')),
            ],
        ),
    ]
