# Generated by Django 3.2.5 on 2021-09-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_clentaddressinformation_clientinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clentaddressinformation',
            name='Email',
            field=models.EmailField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='clentaddressinformation',
            name='Phone',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
