# Generated by Django 3.2.5 on 2021-09-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_bankbranch_bankinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankbranch',
            old_name='Client_Name',
            new_name='Bank_Name',
        ),
        migrations.RenameField(
            model_name='bankinformation',
            old_name='Client_Name',
            new_name='Bank_Name',
        ),
    ]
