# Generated by Django 3.2.7 on 2021-09-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0022_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeessalary',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='employeessalary',
            name='Effect_Date',
        ),
    ]
