# Generated by Django 3.2.7 on 2021-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0023_auto_20210927_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeessalary',
            name='Designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeessalary',
            name='Effect_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
